from PySide6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralWidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.playlist_widget = QtWidgets.QListView(parent=self.centralWidget)
        self.playlist_widget.setObjectName("playlist_widget")
        self.verticalLayout.addWidget(self.playlist_widget)
        self.progress_slider = QtWidgets.QSlider(parent=self.centralWidget)
        self.progress_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.progress_slider.setObjectName("progress_slider")
        self.verticalLayout.addWidget(self.progress_slider)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stop_play_button = QtWidgets.QPushButton(parent=self.centralWidget)
        self.stop_play_button.setObjectName("stop_play_button")
        self.horizontalLayout.addWidget(self.stop_play_button)
        self.dialog_button = QtWidgets.QPushButton(parent=self.centralWidget)
        self.dialog_button.setObjectName("dialog_button")
        self.horizontalLayout.addWidget(self.dialog_button)
        self.append_playlist_button = QtWidgets.QPushButton(parent=self.centralWidget)
        self.append_playlist_button.setObjectName("append_playlist_button")
        self.horizontalLayout.addWidget(self.append_playlist_button)
        self.top_user_button = QtWidgets.QPushButton(parent=self.centralWidget)
        self.top_user_button.setObjectName("top_user_button")
        self.horizontalLayout.addWidget(self.top_user_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.volume_slider = QtWidgets.QSlider(parent=self.centralWidget)
        self.volume_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.volume_slider.setObjectName("volume_slider")
        self.horizontalLayout.addWidget(self.volume_slider)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Музыкальный плеер"))
        self.stop_play_button.setText(_translate("MainWindow", "пауза"))
        self.dialog_button.setText(_translate("MainWindow", "Добавить трек"))
        self.append_playlist_button.setText(_translate("MainWindow", "Добавить папку"))
        self.top_user_button.setText(_translate("MainWindow", "топ"))
